### ISSUE TITLE
Práctica visual studio interfaz gráfica 

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-prototipoxd#1]
[Visual studio interfaz grafica.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-prototipoxd/files/8182369/Visual.studio.interfaz.grafica.pdf)

**Comment by josealfredo79** [comment]
Falta la calificación

**Comment by josealfredo79** [comment]
Falta la calificacion

**Comment by josealfredo79** [comment]
Echo porras para que coloquen aqui la calificación

**Comment by EvelynLopezz** [comment]
Calificación 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado
